# start with: docker compose up -d
# stop with: docker compose down
# Sensor Values can be found under ./SensorValues
# Adjust ip addresses and/or ports

services:
  monitor:
    image: ghcr.io/es-ude/elastic-ai.cloud.applications.monitor:latest
    restart: always
    ports:
      - "80:80"
    environment:
      - HOST_IP=${HOST_IP}
    command:
      - "--broker-address"
      - "127.0.0.1"
      - "--broker-port"
      - "1883"

  ball_challenge:
    image: ghcr.io/es-ude/elastic-ai.cloud.applications.ball_challenge:latest
    restart: always
    volumes:
      - ./SensorValues:/SensorValues
    ports:
      - "81:80"
    environment:
      - HOST_IP=${HOST_IP}
    command:
      - "--broker-address"
      - "127.0.0.1"
      - "--broker-port"
      - "1883"
      - "--camera-address"
      - "127.0.0.1"
