name: "Build Release Packages"
on:
  workflow_dispatch:
  release:
    types:
      - released

permissions:
  contents: read
  packages: write

jobs:
  publish-image:
    name: Publish BallChallenge App as Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Get Release Version
        id: release
        uses: GuillaumeFalourd/get-release-or-tag@v2
      - name: Get Release Artifacts
        uses: Itsblue/download-release-assets-action@v4
        with:
          version: ${{ steps.release.outputs.tag }}
          file: "ballchallenge.jar"
          target: "cloud/app/build/libs"
      - name: Build BallChallenge Image
        working-directory: ./cloud
        env:
          REPOSITORY: ${{ github.repository }}
          RELEASE_TAG: ${{ steps.release.outputs.tag }}
        run: |
          docker build . --file Dockerfile --tag ghcr.io/$REPOSITORY:$RELEASE_TAG --tag ghcr.io/$REPOSITORY:latest
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor  }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Image to Github Container Registry
        run: |
          docker push --all-tags "$REGISTRY_PATH/$GITHUB_REPOSITORY"
